services:
  postgres:
    image: postgres:16
    container_name: tasktracker-postgres
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasktracker-backend
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: tasktracker-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
